# Generated by Selenium IDE
import pytest
from model.user import User
from fixture.application import Application


@pytest.fixture
def app(request):
    fixture = Application()
    request.addfinalizer(fixture.destroy)
    return fixture


def test_create_user(app):
    app.login(login_login="popmedrus@gmail.com", login_password="12345678")
    app.create_user(User(user_name="rh17", user_email="rh17@gmail.com", user_password="12345678"))
    app.logout()





  
