# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRh10():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_rh10(self):
    self.driver.get("http://users.bugred.ru/user/login/index.html")
    self.driver.set_window_size(1279, 784)
    self.driver.find_element(By.NAME, "login").click()
    self.driver.find_element(By.NAME, "login").send_keys("popmedrus@gmail.com")
    self.driver.find_element(By.NAME, "password").send_keys("12345678")
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) .btn").click()
    self.driver.find_element(By.LINK_TEXT, "Добавить пользователя").click()
    self.driver.find_element(By.NAME, "noibiz_name").click()
    self.driver.find_element(By.NAME, "noibiz_name").send_keys("rh12")
    self.driver.find_element(By.NAME, "noibiz_email").click()
    self.driver.find_element(By.NAME, "noibiz_email").send_keys("rh12@gmail.com")
    self.driver.find_element(By.NAME, "noibiz_password").click()
    self.driver.find_element(By.NAME, "noibiz_password").send_keys("12345678")
    self.driver.find_element(By.NAME, "noibiz_birthday").click()
    self.driver.find_element(By.NAME, "noibiz_birthday").send_keys("0001-05-07")
    self.driver.find_element(By.NAME, "noibiz_birthday").send_keys("0019-05-07")
    self.driver.find_element(By.NAME, "noibiz_birthday").send_keys("0199-05-07")
    self.driver.find_element(By.NAME, "noibiz_birthday").send_keys("1995-05-07")
    self.driver.find_element(By.NAME, "noibiz_gender").click()
    dropdown = self.driver.find_element(By.NAME, "noibiz_gender")
    dropdown.find_element(By.XPATH, "//option[. = 'Мужской']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(2)").click()
    self.driver.find_element(By.NAME, "act_create").click()
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.NAME, "q").send_keys("rh12")
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Посмотреть").click()
    self.driver.find_element(By.LINK_TEXT, "popmedrus").click()
    self.driver.find_element(By.LINK_TEXT, "Выход").click()
  
